services:
  - type: web
    name: recipe-scraper-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn scraper:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GEMINI_API_KEY
        sync: false
