services:
  - type: web
    name: scraper-backend
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyAqYGolgMF1Swy6C710QdIQob9HCxU-JcI
    healthCheckPath: /
    autoDeploy: true
